### ISSUE TITLE
Is this the latest version?

### ISSUE THREAD

**Issue by bmarcote** [RTIP/artip#3]
I was interested in trying ARTIP on some uGMRT data after seeing [Gupta et al. (2020; arXiv:2007.04347)](https://arxiv.org/abs/2007.04347). However this repository has not been updated in the last three years. Does this still represents the state-of-the-art of ARTIP or did you move to a different repository?

**Comment by nrjgupta** [comment]
This is an ancient version (prototype) which we are not maintaining anymore.  Also this is not tested on wideband datasets.  The version discussed in Gupta+20 is intended to be made public with the first MALS data release (sometime next year).

**Comment by bmarcote** [comment]
Ok thank you for the prompt answer!
